# Generated by Django 4.1.1 on 2022-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('date_create', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('sales_contact', models.CharField(max_length=100)),
            ],
        ),
    ]
