# Generated by Django 4.1.1 on 2022-09-23 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic_events', '0002_contractstatus_alter_client_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'sales'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('signed', 'Signed'), ('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='status',
            field=models.CharField(choices=[('signed', 'Signed'), ('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'support'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
