# Generated by Django 4.1.1 on 2022-09-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0003_alter_client_sales_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstatus',
            name='contract',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='epic_events.contract'),
        ),
    ]
