# Generated by Django 4.1.1 on 2022-09-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0004_contractstatus_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatus',
            name='contract',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='epic_events.contract'),
        ),
    ]
