# Generated by Django 4.1.1 on 2022-09-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0005_alter_contractstatus_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractstatus',
            name='contract',
        ),
    ]
