# Generated by Django 4.1.1 on 2022-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0006_remove_contractstatus_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatus',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
